### ISSUE TITLE
Roadmap to Milkdown@6.0

### ISSUE THREAD

**Issue by Saul-Mirone** [Saul-Mirone/milkdown#386]
- [x] New theme manager to make theme more powerful
- [x] https://github.com/Saul-Mirone/milkdown/pull/376
- [x] https://github.com/Saul-Mirone/milkdown/issues/375
- [x] https://github.com/Saul-Mirone/milkdown/issues/396
- [x] https://github.com/Saul-Mirone/milkdown/issues/368
- [x] https://github.com/Saul-Mirone/milkdown/pull/424
- [x] https://github.com/Saul-Mirone/milkdown/issues/419
- [x] https://github.com/Saul-Mirone/milkdown/issues/388
- [x] https://github.com/Saul-Mirone/milkdown/pull/422
- [x] https://github.com/Saul-Mirone/milkdown/issues/437
- [x] https://github.com/Saul-Mirone/milkdown/issues/238
- [x] https://github.com/Saul-Mirone/milkdown/pull/347
- [x] https://github.com/Saul-Mirone/milkdown/issues/387
- [x] https://github.com/Saul-Mirone/milkdown/issues/441
- [x] https://github.com/Saul-Mirone/milkdown/issues/445
- [x] https://github.com/Saul-Mirone/milkdown/issues/280
- [x] https://github.com/Saul-Mirone/milkdown/issues/465
- [x] https://github.com/Saul-Mirone/milkdown/issues/379
- [x] https://github.com/Saul-Mirone/milkdown/issues/450
- [x] https://github.com/Saul-Mirone/milkdown/issues/395
- [x] https://github.com/Saul-Mirone/milkdown/issues/289

**Comment by Saul-Mirone** [comment]
All tasks finished and the new version will be released before Apr. 28.
